# Generated by Django 5.2.7 on 2025-11-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/%Y/%m/%d/', verbose_name='Главное фото')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Цвет')),
                ('gender', models.CharField(choices=[('men', 'Мужской'), ('women', 'Женский'), ('unisex', 'Унисекс'), ('kids', 'Детский')], default='unisex', max_length=10, verbose_name='Пол')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Страна производства')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
